name: first_app
description: An application that manages and receives alerts from ActingWeb actors

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_auth0:  
    path: ../flutter-auth0
  #^0.5.0
  cupertino_icons: ^0.1.3
  meta: ^1.1.8
  scoped_model: ^1.0.1
  shared_preferences: ^0.5.6
  geolocator: ^5.1.5
  firebase_core: ^0.4.3+1
  firebase_analytics: ^5.0.9
  firebase_crashlytics: ^0.1.2+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: any
  flutter_launcher_icons: ^0.7.4
  intl_translation: ^0.17.7
  convert: any
  mockito: any

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/actingweb-header-small.png
  fonts:
      - family: Nunito
        fonts:
          - asset: assets/Nunito.ttf
