name: first_app
description: An application that manages and receives alerts from ActingWeb actors

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.4.3+11

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  flutter_appauth: ^1.0.0
  cupertino_icons: ^1.0.3
  meta: ^1.1.8
  provider: ^5.0.0
  shared_preferences: ^2.0.5
  google_maps_flutter: ^2.0.5
  google_maps_flutter_web: ^0.3.0
  geolocator: ^7.0.3
  geocoding: ^2.0.0
  firebase_core: ^1.2.0
  firebase_analytics: ^8.1.0
  firebase_crashlytics: ^2.0.4
  firebase_messaging: ^10.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: ^1.16.8
  flutter_launcher_icons: ^0.9.0
  convert: ^3.0.0
  mockito: ^5.0.8

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/actingweb-header-small.png
  fonts:
    - family: Nunito
      fonts:
        - asset: assets/Nunito.ttf
flutter_intl:
  enabled: true
